#ifndef PHILO_LIBREARY_H
# define PHILO_LIBREARY_H

# define MAX_LEN 26

# define PH_0 "Pythagoras of Samos"
# define PH_1 "Confucius"
# define PH_2 "Permenides"
# define PH_3 "Hypatia of Alexandria"
# define PH_4 "Socrates"
# define PH_5 "Plato"
# define PH_6 "Aristotle"
# define PH_7 "Mary Wollstonecraft"
# define PH_8 "Marcus Aurelius"
# define PH_9 "Zhu Xi"
# define PH_10 "Thomas Hobbes"
# define PH_11 "Hannah Arendt"
# define PH_12 "Machiavelli"
# define PH_13 "Saint Thomas Aquinas"
# define PH_14 "Rene Descartes"
# define PH_15 "Simone de Beauvoir"
# define PH_16 "John Locke"
# define PH_17 "Spinoza"
# define PH_18 "Leibniz"
# define PH_19 "Ada Lovelace"
# define PH_20 "Montesquieu"
# define PH_21 "David Hume"
# define PH_22 "Jean-Jacques Rousseau"
# define PH_23 "Simone Weil"
# define PH_24 "Emmanuel Kant"
# define PH_25 "Hegel"
# define PH_26 "Schopenhauer"
# define PH_27 "christine de Pizan"
# define PH_28 "John Stuart Mill"
# define PH_29 "Karl Marx"
# define PH_30 "Friedrich Nietzsche"
# define PH_31 "Lucrezia Marinella"
# define PH_32 "Ludwig Wittgenstein"
# define PH_33 "Michel Foucault"
# define PH_34 "Sun Tzu"
# define PH_35 "Thales of Miletus"
# define PH_36 "Lady Ann Conway"
# define PH_37 "Heraclitus"
# define PH_38 "Albert Camus"
# define PH_39 "Jean-Paul Sartre"
# define PH_40 "Harriet Taylor Mill"
# define PH_41 "Martin Heidegger"
# define PH_42 "Democritus"
# define PH_43 "Epicurus"
# define PH_44 "Diogenes of Sinope"
# define PH_45 "Émilie du Châtelet"
# define PH_46 "Carl Jung"
# define PH_47 "Sigmund Freud"
# define PH_48 "Vladimir Lenin"
# define PH_49 "Sophie de Condorcet"
# define PH_50 "Charles Darwin"
# define PH_51 "Adam Smith"
# define PH_52 "George Berkeley"
# define PH_53 "Jeanne Hersch"
# define PH_54 "Denis Diderot"
# define PH_55 "Voltaire"
# define PH_56 "Sextus Empiricus"
# define PH_57 "Plotinus"
# define PH_58 "G.E.M. Anscombe"
# define PH_59 "Nicolaus Copernicus"
# define PH_60 "Desiderius Erasmus"
# define PH_61 "Francis Bacon"
# define PH_62 "Iris Murdoch"
# define PH_63 "Galileo Galilei"
# define PH_64 "Sir Isaac Newton"
# define PH_65 "Anna Freud"
# define PH_66 "Marie Curie"
# define PH_67 "Ibn Sina (Avicenna)"
# define PH_68 "Ibn Rushd (Averroes)"
# define PH_69 "Maria Montessori"
# define PH_70 "Mo Tzu"
# define PH_71 "Blaise Pascal"
# define PH_72 "Adi Shankaracharya"
# define PH_73 "Katherine Johnson"
# define PH_74 "Al-Ghazali"
# define PH_75 "Judith Butler"
# define PH_76 "Zhuangzi"
# define PH_77 "Seneca"
# define PH_78 "Jiddu Krishnamurti"
# define PH_79 "Hedy Lamarr"
# define PH_80 "Auguste Comte"
# define PH_81 "Søren Kierkegaard"
# define PH_82 "Karl Popper"
# define PH_83 "Margaret Cavendish"
# define PH_84 "Olympe de Gouges"
# define PH_85 "Edmund Husserl"
# define PH_86 "Madame de Staël"
# define PH_87 "Fatima bint al-Muthanna"
# define PH_88 "Käte Hamburger"
# define PH_89 "Eleonora Ziemięcka"
# define PH_90 "Frantz Fanon"
# define PH_91 "W.E.B. Du Bois"
# define PH_92 "Angela Davis"
# define PH_93 "Aimé Césaire"
# define PH_94 "John Rawls"
# define PH_95 "Frances Wright"
# define PH_96 "Nancy Fraser"
# define PH_97 "Anaximander"
# define PH_98 "Anaximenes"
# define PH_99 "Xenophane"

#endif